import type { DbTrack } from "@/db/schema";

export type Singer = "A" | "B" | "BOTH";

export type LyricLine = {
  at: number;
  end: number;
  singer: Singer;
  text: string;
};

export type Track = {
  id: string;
  title: string;
  artist: string;
  genre: string;
  duration: number;
  durationLabel: string;
  bpm: number;
  key: string;
  cover: string;
  audioUrl?: string;
  color: string;
  accent: string;
  lyrics: LyricLine[];
};

export function dbTrackToTrack(dbTrack: DbTrack): Track {
  return {
    id: dbTrack.id,
    title: dbTrack.title,
    artist: dbTrack.artist,
    genre: dbTrack.genre,
    duration: dbTrack.duration,
    durationLabel: dbTrack.durationLabel,
    bpm: dbTrack.bpm,
    key: dbTrack.key,
    cover: dbTrack.coverUrl,
    audioUrl: dbTrack.audioUrl || undefined,
    color: dbTrack.color,
    accent: dbTrack.accent,
    lyrics: (dbTrack.lyrics as LyricLine[]) || [],
  };
}

export const tracks: Track[] = [
  {
    id: "est-ce-que-tu-maimes",
    title: "Est-ce que tu m'aimes ?",
    artist: "Gims",
    genre: "Pop urbaine",
    duration: 235,
    durationLabel: "3:55",
    bpm: 115,
    key: "E min",
    cover: "/covers/est-ce-que-tu-maimes.jpg",
    audioUrl: "/audio/est-ce-que-tu-maimes.mp3",
    color: "#2563eb",
    accent: "#93c5fd",
    lyrics: [
      { at: 16.0, end: 20.2, singer: "A", text: "J'ai retrouvé le sourire quand j'ai vu le bout du tunnel" },
      { at: 20.2, end: 25.9, singer: "A", text: "Où nous mènera ce jeu du mâle et de la femelle?" },
      { at: 25.9, end: 28.2, singer: "A", text: "Du mâle et de la femelle" },
      { at: 28.2, end: 32.2, singer: "A", text: "On était tellement complices, on a brisé nos complexes" },
      { at: 32.2, end: 37.8, singer: "A", text: "Pour te faire comprendre, t'avais juste à lever le cil" },
      { at: 37.8, end: 39.2, singer: "A", text: "T'avais juste à lever le cil" },
      { at: 39.2, end: 44.4, singer: "A", text: "J'étais prêt à graver ton image à l'encre noire sous mes paupières" },
      { at: 44.4, end: 49.9, singer: "A", text: "Afin de te voir, même dans un sommeil éternel" },
      { at: 49.9, end: 54.0, singer: "A", text: "Même dans un sommeil éternel" },
      { at: 54.0, end: 56.3, singer: "A", text: "Même dans un sommeil éternel" },
      { at: 56.3, end: 60.4, singer: "BOTH", text: "J'étais censé t'aimer, mais j'ai vu l'averse" },
      { at: 60.4, end: 64.4, singer: "BOTH", text: "J'ai cligné des yeux, tu n'étais plus la même" },
      { at: 64.4, end: 68.0, singer: "BOTH", text: "Est-ce que je t'aime? J'sais pas si je t'aime" },
      { at: 68.0, end: 72.3, singer: "BOTH", text: "Est-ce que tu m'aimes? J'sais pas si je t'aime" },
      { at: 72.3, end: 76.3, singer: "BOTH", text: "J'étais censé t'aimer, mais j'ai vu l'averse" },
      { at: 76.3, end: 80.4, singer: "BOTH", text: "J'ai cligné des yeux, tu n'étais plus la même" },
      { at: 80.4, end: 84.2, singer: "BOTH", text: "Est-ce que je t'aime? J'sais pas si je t'aime" },
      { at: 84.2, end: 88.1, singer: "BOTH", text: "Est-ce que tu m'aimes? J'sais pas si je t'aime" },
      { at: 88.1, end: 92.1, singer: "B", text: "Pour t'éviter de souffrir, j'n'avais qu'à te dire \"je t'aime\"" },
      { at: 92.1, end: 97.9, singer: "B", text: "Ça m'a fait mal de t'faire mal, je n'ai jamais autant souffert" },
      { at: 97.9, end: 100.0, singer: "B", text: "Je n'ai jamais autant souffert" },
      { at: 100.0, end: 104.6, singer: "B", text: "Quand j't'ai mis la bague au doigt, j'me suis passé les bracelets" },
      { at: 104.6, end: 109.7, singer: "B", text: "Pendant ce temps, le temps passe, et je subis tes balivernes" },
      { at: 109.7, end: 111.4, singer: "B", text: "Et je subis tes balivernes" },
      { at: 111.4, end: 116.4, singer: "B", text: "J'étais prêt à graver ton image à l'encre noire sous mes paupières" },
      { at: 116.4, end: 122.0, singer: "B", text: "Afin de te voir, même dans un sommeil éternel" },
      { at: 122.0, end: 126.2, singer: "A", text: "Même dans un sommeil éternel" },
      { at: 126.2, end: 128.5, singer: "A", text: "Même dans un sommeil éternel" },
      { at: 128.5, end: 132.8, singer: "BOTH", text: "J'étais censé t'aimer, mais j'ai vu l'averse" },
      { at: 132.8, end: 136.7, singer: "BOTH", text: "J'ai cligné des yeux, tu n'étais plus la même" },
      { at: 136.7, end: 140.1, singer: "BOTH", text: "Est-ce que je t'aime? J'sais pas si je t'aime" },
      { at: 140.1, end: 144.6, singer: "BOTH", text: "Est-ce que tu m'aimes? J'sais pas si je t'aime" },
      { at: 144.6, end: 148.9, singer: "BOTH", text: "J'étais censé t'aimer, mais j'ai vu l'averse" },
      { at: 148.9, end: 152.6, singer: "BOTH", text: "J'ai cligné des yeux, tu n'étais plus la même" },
      { at: 152.6, end: 155.7, singer: "BOTH", text: "Est-ce que je t'aime? J'sais pas si je t'aime" },
      { at: 155.7, end: 165.9, singer: "BOTH", text: "Est-ce que tu m'aimes? J'sais pas si je t'aime" },
      { at: 165.9, end: 174.1, singer: "A", text: "J'sais pas si je t'aime" },
      { at: 174.1, end: 175.3, singer: "B", text: "J'sais pas si je t'aime" },
      { at: 175.3, end: 179.2, singer: "A", text: "Je m'suis fais mal en m'envolant, j'n'avais pas vu l'plafond de verre" },
      { at: 179.2, end: 185.2, singer: "B", text: "Tu me trouverais ennuyeux si je t'aimais à ta manière" },
      { at: 185.2, end: 189.4, singer: "BOTH", text: "J'étais censé t'aimer, mais j'ai vu l'averse" },
      { at: 189.4, end: 193.3, singer: "BOTH", text: "J'ai cligné des yeux, tu n'étais plus la même" },
      { at: 193.3, end: 196.7, singer: "BOTH", text: "Est-ce que je t'aime? J'sais pas si je t'aime" },
      { at: 196.7, end: 201.2, singer: "BOTH", text: "Est-ce que tu m'aimes? J'sais pas si je t'aime" },
      { at: 201.2, end: 205.6, singer: "BOTH", text: "J'étais censé t'aimer, mais j'ai vu l'averse" },
      { at: 205.6, end: 209.6, singer: "BOTH", text: "J'ai cligné des yeux, tu n'étais plus la même" },
      { at: 209.6, end: 213.1, singer: "BOTH", text: "Est-ce que je t'aime? J'sais pas si je t'aime" },
      { at: 213.1, end: 220.0, singer: "BOTH", text: "Est-ce que tu m'aimes? J'sais pas si je t'aime" },
    ],
  },
  {
    id: "afro-trap-part-7",
    title: "Afro Trap Pt. 7 (La puissance)",
    artist: "MHD",
    genre: "Afro Trap",
    duration: 140,
    durationLabel: "2:20",
    bpm: 130,
    key: "F# min",
    cover: "/covers/afro-trap-part-7.jpg",
    audioUrl: "/audio/afro-trap-part-7.mp3",
    color: "#e11d48",
    accent: "#fda4af",
    lyrics: [
      { at: 2.9, end: 6.1, singer: "A", text: "Ah Puissanci" },
      { at: 6.1, end: 8.1, singer: "A", text: "MHD Puissanci" },
      { at: 8.1, end: 9.8, singer: "A", text: "La puissance, que la puissance" },
      { at: 9.8, end: 12.0, singer: "A", text: "J'ai pas connu la défaite depuis mon existence" },
      { at: 12.0, end: 13.9, singer: "A", text: "Gros, j'm'en sors bien, suis-je un miraculé?" },
      { at: 13.9, end: 16.2, singer: "A", text: "Parle en français, parle en cash ou prends tes distances" },
      { at: 16.2, end: 17.8, singer: "A", text: "Ramenez-moi la tête, je reste content, passe un tabac" },
      { at: 17.8, end: 19.6, singer: "A", text: "Qu'est-ce qu'tu m'parles? Dans ta zone, t'es qu'un guetteur" },
      { at: 19.6, end: 22.1, singer: "A", text: "Ceux qui pensent me connaître me connaissent pas" },
      { at: 22.1, end: 24.7, singer: "A", text: "Maintenant, j'suis rodave comme les bacqueux dans mon secteur" },
      { at: 24.7, end: 28.6, singer: "B", text: "T'es dans la merde, j'suis au fond d'un carré V.I.P, ces bâtards sont à la dèche" },
      { at: 28.6, end: 32.4, singer: "B", text: "T'es mon adversaire, t'as pas d'chance, tu veux tej' la bouteille à la mer" },
      { at: 32.4, end: 36.4, singer: "B", text: "Où sont les vrais? Ceux qui parlent peu, ils frappent fort, à l'affût de tous les dièses" },
      { at: 36.4, end: 41.2, singer: "B", text: "Recule-toi et laisse-moi faire, quand les opposés s'attirent mon gars, c'est là que les balles se perdent" },
      { at: 41.2, end: 44.2, singer: "B", text: "Rien qu'elles s'perdent et même toi, t'es du-per, toujours attendu comme un rayon d'soleil" },
      { at: 44.2, end: 48.1, singer: "BOTH", text: "Gros, c'est la puissance, rien que la puissance, respecte le protocole, gros y'a pas d'secret" },
      { at: 48.1, end: 49.7, singer: "BOTH", text: "La puissance (paw paw)" },
      { at: 49.7, end: 52.1, singer: "BOTH", text: "Gros, c'est la puissance, c'est la puissance" },
      { at: 52.1, end: 53.7, singer: "BOTH", text: "La puissance" },
      { at: 53.7, end: 56.0, singer: "BOTH", text: "Gros, c'est la puissance, c'est la puissance" },
      { at: 56.0, end: 57.7, singer: "BOTH", text: "La puissance" },
      { at: 57.7, end: 60.0, singer: "BOTH", text: "Gros, c'est la puissance, c'est la puissance" },
      { at: 60.0, end: 61.7, singer: "BOTH", text: "La puissance" },
      { at: 61.7, end: 64.1, singer: "BOTH", text: "Gros, c'est la puissance, c'est la puissance" },
      { at: 64.1, end: 66.0, singer: "A", text: "Ça revient plus fort, j'suis toujours le même" },
      { at: 66.0, end: 68.1, singer: "A", text: "C'est moi contre moi, toi tu finis par terre" },
      { at: 68.1, end: 69.9, singer: "A", text: "Mon bigo sonne, j'suis en mode avion" },
      { at: 69.9, end: 71.6, singer: "A", text: "Pour qu'j'arrête, faut qu'on m'tranche les cordes vocales" },
      { at: 71.6, end: 75.7, singer: "A", text: "Ça blesse, MHD, Afro Trap partie 7, le projet est dans les bacs" },
      { at: 75.7, end: 80.0, singer: "A", text: "J'ai la grinta, tout est bon, oui tout est félé, la Moula Gang n'oubliera pas" },
      { at: 80.0, end: 83.9, singer: "A", text: "J'ai rien vu, j'ai rien entendu, j'ai rien dit, mais du sale je vous promets" },
      { at: 83.9, end: 88.2, singer: "B", text: "Tu m'attendais, cálmate, j'arrive, 2017, on reprend les hostilités" },
      { at: 88.2, end: 93.5, singer: "B", text: "Ils ont voulu m'boycotte sans y arriver, seul Dieu pourra m'en protéger" },
      { at: 93.5, end: 97.3, singer: "B", text: "Le chemin est long, je compte plus d'ennemis que d'alliés" },
      { at: 97.3, end: 101.1, singer: "B", text: "J'suis seul, j'ai besoin d'personne" },
      { at: 101.1, end: 104.0, singer: "B", text: "M'man prie pour moi, offensive est la guerre, ils l'auront tôt ou tard" },
      { at: 104.0, end: 105.7, singer: "BOTH", text: "La puissance (wouh)" },
      { at: 105.7, end: 108.1, singer: "BOTH", text: "Gros, c'est la puissance, c'est la puissance" },
      { at: 108.1, end: 109.7, singer: "BOTH", text: "La puissance" },
      { at: 109.7, end: 112.1, singer: "BOTH", text: "Gros, c'est la puissance, c'est la puissance" },
      { at: 112.1, end: 113.7, singer: "BOTH", text: "La puissance" },
      { at: 113.7, end: 116.1, singer: "BOTH", text: "Gros, c'est la puissance, c'est la puissance" },
      { at: 116.1, end: 117.7, singer: "BOTH", text: "La puissance" },
      { at: 117.7, end: 122.0, singer: "BOTH", text: "Gros, c'est la puissance, c'est la puissance" },
    ],
  },
  {
    id: "minuit-zero",
    title: "Minuit Zéro",
    artist: "Nova & Sway",
    genre: "Pop urbaine",
    duration: 72,
    durationLabel: "1:12",
    bpm: 104,
    key: "F min",
    cover: "/covers/minuit-zero.svg",
    color: "#ef3f8f",
    accent: "#ffbfdc",
    lyrics: [
      { at: 0, end: 5, singer: "BOTH", text: "Respire… le duel commence" },
      { at: 5, end: 10, singer: "A", text: "J'ai laissé la ville allumée derrière moi" },
      { at: 10, end: 15, singer: "A", text: "Les néons me suivent mais je n'les entends pas" },
      { at: 15, end: 20, singer: "B", text: "Tu cours après l'heure, moi je danse avec elle" },
      { at: 20, end: 25, singer: "B", text: "Nos ombres se répondent sous la lune artificielle" },
      { at: 25, end: 30, singer: "A", text: "Si demain nous oublie, reste encore un peu" },
      { at: 30, end: 35, singer: "B", text: "On remet les compteurs à minuit zéro" },
      { at: 35, end: 40, singer: "A", text: "Plus rien à promettre, plus rien dans les poches" },
      { at: 40, end: 45, singer: "B", text: "Seulement cette musique qui nous rapproche" },
      { at: 45, end: 51, singer: "BOTH", text: "Minuit zéro — on recommence tout" },
      { at: 51, end: 57, singer: "A", text: "Ta voix dans le noir me ramène à nous" },
      { at: 57, end: 63, singer: "B", text: "Minuit zéro — le monde peut attendre" },
      { at: 63, end: 69, singer: "BOTH", text: "Encore une seconde avant de redescendre" },
      { at: 69, end: 72, singer: "BOTH", text: "Minuit… zéro" },
    ],
  },
  {
    id: "coeur-laser",
    title: "Cœur Laser",
    artist: "Léna K. feat. Milo",
    genre: "Électro pop",
    duration: 78,
    durationLabel: "1:18",
    bpm: 122,
    key: "C min",
    cover: "/covers/coeur-laser.svg",
    color: "#5046e5",
    accent: "#b8b4ff",
    lyrics: [
      { at: 0, end: 5, singer: "BOTH", text: "Trois, deux, un — lumière" },
      { at: 5, end: 11, singer: "A", text: "Tu me regardes en ultraviolet" },
      { at: 11, end: 17, singer: "B", text: "Je lis tes messages dans les reflets" },
      { at: 17, end: 23, singer: "A", text: "La nuit nous dessine en lignes parfaites" },
      { at: 23, end: 29, singer: "B", text: "Un battement de trop et tout s'arrête" },
      { at: 29, end: 35, singer: "BOTH", text: "Cœur laser, vise-moi encore" },
      { at: 35, end: 41, singer: "BOTH", text: "Fais monter la lumière plus fort" },
      { at: 41, end: 47, singer: "A", text: "Pas besoin de filtre, pas besoin de décor" },
      { at: 47, end: 53, singer: "B", text: "Quand le silence tombe, on danse encore" },
      { at: 53, end: 59, singer: "A", text: "Éclair rouge sur nos deux visages" },
      { at: 59, end: 65, singer: "B", text: "On se retrouve au milieu de l'orage" },
      { at: 65, end: 73, singer: "BOTH", text: "Cœur laser, cœur laser, traverse la nuit" },
      { at: 73, end: 78, singer: "BOTH", text: "Et ramène-moi ici" },
    ],
  },
  {
    id: "sans-reseau",
    title: "Sans Réseau",
    artist: "Yanis Blue",
    genre: "Pop solaire",
    duration: 76,
    durationLabel: "1:16",
    bpm: 112,
    key: "A maj",
    cover: "/covers/sans-reseau.svg",
    color: "#ff6d4a",
    accent: "#ffd25e",
    lyrics: [
      { at: 0, end: 5, singer: "BOTH", text: "Fenêtres ouvertes, volume à fond" },
      { at: 5, end: 11, singer: "A", text: "J'ai mis le téléphone en mode avion" },
      { at: 11, end: 17, singer: "B", text: "La route nous appelle, on change de direction" },
      { at: 17, end: 23, singer: "A", text: "Du soleil plein les yeux, du vent dans les chansons" },
      { at: 23, end: 29, singer: "B", text: "On n'a besoin de rien, juste un peu d'horizon" },
      { at: 29, end: 35, singer: "BOTH", text: "Sans réseau, sans regrets" },
      { at: 35, end: 41, singer: "A", text: "On roule jusqu'où la mer disparaît" },
      { at: 41, end: 47, singer: "B", text: "Sans réseau, promets-moi" },
      { at: 47, end: 53, singer: "BOTH", text: "Qu'on ne rentrera pas cette fois" },
      { at: 53, end: 59, singer: "A", text: "La nuit arrive mais personne ne freine" },
      { at: 59, end: 65, singer: "B", text: "On garde les souvenirs, on perd les antennes" },
      { at: 65, end: 71, singer: "BOTH", text: "Sans réseau, le monde est à nous" },
      { at: 71, end: 76, singer: "BOTH", text: "Chante plus fort jusqu'au bout" },
    ],
  },
  {
    id: "dernier-metro",
    title: "Dernier Métro",
    artist: "Kairo 18",
    genre: "Rap mélodique",
    duration: 80,
    durationLabel: "1:20",
    bpm: 92,
    key: "D min",
    cover: "/covers/dernier-metro.svg",
    color: "#b8e42d",
    accent: "#e8ff94",
    lyrics: [
      { at: 0, end: 5, singer: "BOTH", text: "Attention à la fermeture des portes" },
      { at: 5, end: 11, singer: "A", text: "J'ai raté le dernier métro pour écrire seize mesures" },
      { at: 11, end: 17, singer: "A", text: "La ville vide a des secrets sur chaque mur" },
      { at: 17, end: 23, singer: "B", text: "Tu parles de demain comme si tout était sûr" },
      { at: 23, end: 29, singer: "B", text: "Moi j'avance sans ticket, le regard un peu dur" },
      { at: 29, end: 35, singer: "A", text: "Quai désert, cœur plein, j'attends pas le signal" },
      { at: 35, end: 41, singer: "B", text: "Chaque détour me rapproche du point final" },
      { at: 41, end: 47, singer: "A", text: "Les tunnels font l'écho de tout ce qu'on vaut" },
      { at: 47, end: 53, singer: "B", text: "On remonte à la surface au dernier métro" },
      { at: 53, end: 59, singer: "A", text: "J'ai la cadence lourde et les idées claires" },
      { at: 59, end: 65, singer: "B", text: "Tu as le feu tranquille, j'ai l'étincelle en l'air" },
      { at: 65, end: 72, singer: "BOTH", text: "Dernier métro, personne sur le quai" },
      { at: 72, end: 80, singer: "BOTH", text: "Deux voix dans la rame, impossible d'arrêter" },
    ],
  },
];

export function getTrack(trackId: string) {
  return tracks.find((track) => track.id === trackId);
}
