import type { DbTrack } from "@/db/schema";

export type Singer = "A" | "B" | "BOTH";

export type LyricLine = {
  at: number;
  end: number;
  singer: Singer;
  text: string;
};

export type Track = {
  id: string;
  title: string;
  artist: string;
  genre: string;
  duration: number;
  durationLabel: string;
  bpm: number;
  key: string;
  cover: string;
  audioUrl?: string;
  color: string;
  accent: string;
  lyrics: LyricLine[];
};

export function dbTrackToTrack(dbTrack: DbTrack): Track {
  return {
    id: dbTrack.id,
    title: dbTrack.title,
    artist: dbTrack.artist,
    genre: dbTrack.genre,
    duration: dbTrack.duration,
    durationLabel: dbTrack.durationLabel,
    bpm: dbTrack.bpm,
    key: dbTrack.key,
    cover: dbTrack.coverUrl,
    audioUrl: dbTrack.audioUrl || undefined,
    color: dbTrack.color,
    accent: dbTrack.accent,
    lyrics: (dbTrack.lyrics as LyricLine[]) || [],
  };
}

export const tracks: Track[] = [
  {
    id: "est-ce-que-tu-maimes",
    title: "Est-ce que tu m'aimes ?",
    artist: "Gims",
    genre: "Pop urbaine",
    duration: 235,
    durationLabel: "3:55",
    bpm: 115,
    key: "E min",
    cover: "/covers/est-ce-que-tu-maimes.jpg",
    audioUrl: "/audio/est-ce-que-tu-maimes.mp3",
    color: "#2563eb",
    accent: "#93c5fd",
    lyrics: [
      { at: 16.0, end: 20.2, singer: "A", text: "J'ai retrouvé le sourire quand j'ai vu le bout du tunnel" },
      { at: 20.2, end: 25.9, singer: "A", text: "Où nous mènera ce jeu du mâle et de la femelle?" },
      { at: 25.9, end: 28.2, singer: "A", text: "Du mâle et de la femelle" },
      { at: 28.2, end: 32.2, singer: "A", text: "On était tellement complices, on a brisé nos complexes" },
      { at: 32.2, end: 37.8, singer: "A", text: "Pour te faire comprendre, t'avais juste à lever le cil" },
      { at: 37.8, end: 39.2, singer: "A", text: "T'avais juste à lever le cil" },
      { at: 39.2, end: 44.4, singer: "A", text: "J'étais prêt à graver ton image à l'encre noire sous mes paupières" },
      { at: 44.4, end: 49.9, singer: "A", text: "Afin de te voir, même dans un sommeil éternel" },
      { at: 49.9, end: 54.0, singer: "A", text: "Même dans un sommeil éternel" },
      { at: 54.0, end: 56.3, singer: "A", text: "Même dans un sommeil éternel" },
      { at: 56.3, end: 60.4, singer: "BOTH", text: "J'étais censé t'aimer, mais j'ai vu l'averse" },
      { at: 60.4, end: 64.4, singer: "BOTH", text: "J'ai cligné des yeux, tu n'étais plus la même" },
      { at: 64.4, end: 68.0, singer: "BOTH", text: "Est-ce que je t'aime? J'sais pas si je t'aime" },
      { at: 68.0, end: 72.3, singer: "BOTH", text: "Est-ce que tu m'aimes? J'sais pas si je t'aime" },
      { at: 72.3, end: 76.3, singer: "BOTH", text: "J'étais censé t'aimer, mais j'ai vu l'averse" },
      { at: 76.3, end: 80.4, singer: "BOTH", text: "J'ai cligné des yeux, tu n'étais plus la même" },
      { at: 80.4, end: 84.2, singer: "BOTH", text: "Est-ce que je t'aime? J'sais pas si je t'aime" },
      { at: 84.2, end: 88.1, singer: "BOTH", text: "Est-ce que tu m'aimes? J'sais pas si je t'aime" },
      { at: 88.1, end: 92.1, singer: "B", text: "Pour t'éviter de souffrir, j'n'avais qu'à te dire \"je t'aime\"" },
      { at: 92.1, end: 97.9, singer: "B", text: "Ça m'a fait mal de t'faire mal, je n'ai jamais autant souffert" },
      { at: 97.9, end: 100.0, singer: "B", text: "Je n'ai jamais autant souffert" },
      { at: 100.0, end: 104.6, singer: "B", text: "Quand j't'ai mis la bague au doigt, j'me suis passé les bracelets" },
      { at: 104.6, end: 109.7, singer: "B", text: "Pendant ce temps, le temps passe, et je subis tes balivernes" },
      { at: 109.7, end: 111.4, singer: "B", text: "Et je subis tes balivernes" },
      { at: 111.4, end: 116.4, singer: "B", text: "J'étais prêt à graver ton image à l'encre noire sous mes paupières" },
      { at: 116.4, end: 122.0, singer: "B", text: "Afin de te voir, même dans un sommeil éternel" },
      { at: 122.0, end: 126.2, singer: "A", text: "Même dans un sommeil éternel" },
      { at: 126.2, end: 128.5, singer: "A", text: "Même dans un sommeil éternel" },
      { at: 128.5, end: 132.8, singer: "BOTH", text: "J'étais censé t'aimer, mais j'ai vu l'averse" },
      { at: 132.8, end: 136.7, singer: "BOTH", text: "J'ai cligné des yeux, tu n'étais plus la même" },
      { at: 136.7, end: 140.1, singer: "BOTH", text: "Est-ce que je t'aime? J'sais pas si je t'aime" },
      { at: 140.1, end: 144.6, singer: "BOTH", text: "Est-ce que tu m'aimes? J'sais pas si je t'aime" },
      { at: 144.6, end: 148.9, singer: "BOTH", text: "J'étais censé t'aimer, mais j'ai vu l'averse" },
      { at: 148.9, end: 152.6, singer: "BOTH", text: "J'ai cligné des yeux, tu n'étais plus la même" },
      { at: 152.6, end: 155.7, singer: "BOTH", text: "Est-ce que je t'aime? J'sais pas si je t'aime" },
      { at: 155.7, end: 165.9, singer: "BOTH", text: "Est-ce que tu m'aimes? J'sais pas si je t'aime" },
      { at: 165.9, end: 174.1, singer: "A", text: "J'sais pas si je t'aime" },
      { at: 174.1, end: 175.3, singer: "B", text: "J'sais pas si je t'aime" },
      { at: 175.3, end: 179.2, singer: "A", text: "Je m'suis fais mal en m'envolant, j'n'avais pas vu l'plafond de verre" },
      { at: 179.2, end: 185.2, singer: "B", text: "Tu me trouverais ennuyeux si je t'aimais à ta manière" },
      { at: 185.2, end: 189.4, singer: "BOTH", text: "J'étais censé t'aimer, mais j'ai vu l'averse" },
      { at: 189.4, end: 193.3, singer: "BOTH", text: "J'ai cligné des yeux, tu n'étais plus la même" },
      { at: 193.3, end: 196.7, singer: "BOTH", text: "Est-ce que je t'aime? J'sais pas si je t'aime" },
      { at: 196.7, end: 201.2, singer: "BOTH", text: "Est-ce que tu m'aimes? J'sais pas si je t'aime" },
      { at: 201.2, end: 205.6, singer: "BOTH", text: "J'étais censé t'aimer, mais j'ai vu l'averse" },
      { at: 205.6, end: 209.6, singer: "BOTH", text: "J'ai cligné des yeux, tu n'étais plus la même" },
      { at: 209.6, end: 213.1, singer: "BOTH", text: "Est-ce que je t'aime? J'sais pas si je t'aime" },
      { at: 213.1, end: 220.0, singer: "BOTH", text: "Est-ce que tu m'aimes? J'sais pas si je t'aime" },
    ],
  },
  {
    id: "afro-trap-part-7",
    title: "Afro Trap Pt. 7 (La puissance)",
    artist: "MHD",
    genre: "Afro Trap",
    duration: 140,
    durationLabel: "2:20",
    bpm: 130,
    key: "F# min",
    cover: "/covers/afro-trap-part-7.jpg",
    audioUrl: "/audio/afro-trap-part-7.mp3",
    color: "#e11d48",
    accent: "#fda4af",
    lyrics: [
      { at: 2.9, end: 6.1, singer: "A", text: "Ah Puissanci" },
      { at: 6.1, end: 8.1, singer: "A", text: "MHD Puissanci" },
      { at: 8.1, end: 9.8, singer: "A", text: "La puissance, que la puissance" },
      { at: 9.8, end: 12.0, singer: "A", text: "J'ai pas connu la défaite depuis mon existence" },
      { at: 12.0, end: 13.9, singer: "A", text: "Gros, j'm'en sors bien, suis-je un miraculé?" },
      { at: 13.9, end: 16.2, singer: "A", text: "Parle en français, parle en cash ou prends tes distances" },
      { at: 16.2, end: 17.8, singer: "A", text: "Ramenez-moi la tête, je reste content, passe un tabac" },
      { at: 17.8, end: 19.6, singer: "A", text: "Qu'est-ce qu'tu m'parles? Dans ta zone, t'es qu'un guetteur" },
      { at: 19.6, end: 22.1, singer: "A", text: "Ceux qui pensent me connaître me connaissent pas" },
      { at: 22.1, end: 24.7, singer: "A", text: "Maintenant, j'suis rodave comme les bacqueux dans mon secteur" },
      { at: 24.7, end: 28.6, singer: "B", text: "T'es dans la merde, j'suis au fond d'un carré V.I.P, ces bâtards sont à la dèche" },
      { at: 28.6, end: 32.4, singer: "B", text: "T'es mon adversaire, t'as pas d'chance, tu veux tej' la bouteille à la mer" },
      { at: 32.4, end: 36.4, singer: "B", text: "Où sont les vrais? Ceux qui parlent peu, ils frappent fort, à l'affût de tous les dièses" },
      { at: 36.4, end: 41.2, singer: "B", text: "Recule-toi et laisse-moi faire, quand les opposés s'attirent mon gars, c'est là que les balles se perdent" },
      { at: 41.2, end: 44.2, singer: "B", text: "Rien qu'elles s'perdent et même toi, t'es du-per, toujours attendu comme un rayon d'soleil" },
      { at: 44.2, end: 48.1, singer: "BOTH", text: "Gros, c'est la puissance, rien que la puissance, respecte le protocole, gros y'a pas d'secret" },
      { at: 48.1, end: 49.7, singer: "BOTH", text: "La puissance (paw paw)" },
      { at: 49.7, end: 52.1, singer: "BOTH", text: "Gros, c'est la puissance, c'est la puissance" },
      { at: 52.1, end: 53.7, singer: "BOTH", text: "La puissance" },
      { at: 53.7, end: 56.0, singer: "BOTH", text: "Gros, c'est la puissance, c'est la puissance" },
      { at: 56.0, end: 57.7, singer: "BOTH", text: "La puissance" },
      { at: 57.7, end: 60.0, singer: "BOTH", text: "Gros, c'est la puissance, c'est la puissance" },
      { at: 60.0, end: 61.7, singer: "BOTH", text: "La puissance" },
      { at: 61.7, end: 64.1, singer: "BOTH", text: "Gros, c'est la puissance, c'est la puissance" },
      { at: 64.1, end: 66.0, singer: "A", text: "Ça revient plus fort, j'suis toujours le même" },
      { at: 66.0, end: 68.1, singer: "A", text: "C'est moi contre moi, toi tu finis par terre" },
      { at: 68.1, end: 69.9, singer: "A", text: "Mon bigo sonne, j'suis en mode avion" },
      { at: 69.9, end: 71.6, singer: "A", text: "Pour qu'j'arrête, faut qu'on m'tranche les cordes vocales" },
      { at: 71.6, end: 75.7, singer: "A", text: "Ça blesse, MHD, Afro Trap partie 7, le projet est dans les bacs" },
      { at: 75.7, end: 80.0, singer: "A", text: "J'ai la grinta, tout est bon, oui tout est félé, la Moula Gang n'oubliera pas" },
      { at: 80.0, end: 83.9, singer: "A", text: "J'ai rien vu, j'ai rien entendu, j'ai rien dit, mais du sale je vous promets" },
      { at: 83.9, end: 88.2, singer: "B", text: "Tu m'attendais, cálmate, j'arrive, 2017, on reprend les hostilités" },
      { at: 88.2, end: 93.5, singer: "B", text: "Ils ont voulu m'boycotte sans y arriver, seul Dieu pourra m'en protéger" },
      { at: 93.5, end: 97.3, singer: "B", text: "Le chemin est long, je compte plus d'ennemis que d'alliés" },
      { at: 97.3, end: 101.1, singer: "B", text: "J'suis seul, j'ai besoin d'personne" },
      { at: 101.1, end: 104.0, singer: "B", text: "M'man prie pour moi, offensive est la guerre, ils l'auront tôt ou tard" },
      { at: 104.0, end: 105.7, singer: "BOTH", text: "La puissance (wouh)" },
      { at: 105.7, end: 108.1, singer: "BOTH", text: "Gros, c'est la puissance, c'est la puissance" },
      { at: 108.1, end: 109.7, singer: "BOTH", text: "La puissance" },
      { at: 109.7, end: 112.1, singer: "BOTH", text: "Gros, c'est la puissance, c'est la puissance" },
      { at: 112.1, end: 113.7, singer: "BOTH", text: "La puissance" },
      { at: 113.7, end: 116.1, singer: "BOTH", text: "Gros, c'est la puissance, c'est la puissance" },
      { at: 116.1, end: 117.7, singer: "BOTH", text: "La puissance" },
      { at: 117.7, end: 122.0, singer: "BOTH", text: "Gros, c'est la puissance, c'est la puissance" },
    ],
  },
  {
    id: "belle",
    title: "Belle",
    artist: "GIMS, Dadju & Slimane",
    genre: "Variété / Pop",
    duration: 266,
    durationLabel: "4:26",
    bpm: 72,
    key: "A min",
    cover: "/covers/belle.jpg",
    audioUrl: "/audio/belle.mp3",
    color: "#7c3aed",
    accent: "#c4b5fd",
    lyrics: [
      { at: 0.6, end: 2.3, singer: "A", text: "Belle" },
      { at: 2.3, end: 8.0, singer: "A", text: "C'est un mot qu'on dirait inventé pour elle" },
      { at: 8.0, end: 13.9, singer: "A", text: "Quand elle danse et qu'elle met son corps à jour, tel" },
      { at: 13.9, end: 19.6, singer: "A", text: "Un oiseau qui étend ses ailes pour s'envoler" },
      { at: 19.6, end: 25.3, singer: "A", text: "Alors je sens l'Enfer s'ouvrir sous mes pieds" },
      { at: 25.3, end: 30.9, singer: "A", text: "J'ai posé mes yeux sous sa robe de gitane" },
      { at: 30.9, end: 36.3, singer: "A", text: "À quoi me sert encore de prier Notre-Dame?" },
      { at: 36.3, end: 38.1, singer: "A", text: "Quel" },
      { at: 38.1, end: 44.1, singer: "A", text: "Est celui qui lui jettera la première pierre?" },
      { at: 44.1, end: 49.6, singer: "A", text: "Celui-là ne mérite pas d'être sur terre" },
      { at: 49.6, end: 55.2, singer: "A", text: "Ô Lucifer, ô laisse-moi rien qu'une fois" },
      { at: 55.2, end: 62.0, singer: "A", text: "Glisser mes doigts dans les cheveux d'Esméralda" },
      { at: 70.5, end: 72.4, singer: "B", text: "Belle" },
      { at: 72.4, end: 78.2, singer: "B", text: "Est-ce le diable qui s'est incarné en elle" },
      { at: 78.2, end: 84.0, singer: "B", text: "Pour détourner mes yeux du Dieu éternel?" },
      { at: 84.0, end: 89.9, singer: "B", text: "Qui a mis dans mon être ce désir charnel" },
      { at: 89.9, end: 95.3, singer: "B", text: "Pour m'empêcher de regarder vers le Ciel?" },
      { at: 95.3, end: 101.1, singer: "B", text: "Elle porte en elle le péché originel" },
      { at: 101.1, end: 106.3, singer: "B", text: "La désirer fait-il de moi un criminel?" },
      { at: 106.3, end: 108.4, singer: "B", text: "Celle" },
      { at: 108.4, end: 114.1, singer: "B", text: "Qu'on prenait pour une fille de joie, une fille de rien" },
      { at: 114.1, end: 119.8, singer: "B", text: "Semble soudain porter la croix du genre humain" },
      { at: 119.8, end: 125.4, singer: "B", text: "Ô Notre-Dame, ô laisse-moi rien qu'une fois" },
      { at: 125.4, end: 132.8, singer: "B", text: "Pousser la porte du jardin d'Esméralda" },
      { at: 140.7, end: 142.4, singer: "A", text: "Belle" },
      { at: 142.4, end: 148.0, singer: "A", text: "Malgré ses grands yeux noirs qui vous ensorcellent" },
      { at: 148.0, end: 154.0, singer: "A", text: "La demoiselle serait-elle encore pucelle?" },
      { at: 154.0, end: 159.6, singer: "A", text: "Quand ses mouvements me font voir monts et merveilles" },
      { at: 159.6, end: 165.4, singer: "A", text: "Sous son jupon aux couleurs de l'arc-en-ciel" },
      { at: 165.4, end: 171.2, singer: "B", text: "Ma dulcinée laissez-moi vous être infidèle" },
      { at: 171.2, end: 176.3, singer: "B", text: "Avant de vous avoir mené jusqu'à l'autel" },
      { at: 176.3, end: 178.4, singer: "B", text: "Quel" },
      { at: 178.4, end: 183.8, singer: "B", text: "Est l'homme qui détournerait son regard d'elle" },
      { at: 183.8, end: 189.7, singer: "B", text: "Sous peine d'être changé en statue de sel?" },
      { at: 189.7, end: 195.3, singer: "B", text: "Ô Fleur-de-Lys, j'aimerais être homme de foi" },
      { at: 195.3, end: 202.0, singer: "B", text: "J'irai cueillir la fleur d'amour d'Esméralda" },
      { at: 212.3, end: 218.3, singer: "BOTH", text: "J'ai posé mes yeux sous sa robe de gitane" },
      { at: 218.3, end: 223.3, singer: "BOTH", text: "À quoi me sert encore de prier Notre-Dame?" },
      { at: 223.3, end: 225.4, singer: "BOTH", text: "Quel" },
      { at: 225.4, end: 231.1, singer: "BOTH", text: "Est celui qui lui jettera la première pierre" },
      { at: 231.1, end: 236.7, singer: "BOTH", text: "Celui-là ne mérite pas d'être sur terre" },
      { at: 236.7, end: 242.4, singer: "BOTH", text: "Ô, ô-ô-ô, laisse-moi rien qu'une fois" },
      { at: 242.4, end: 251.5, singer: "BOTH", text: "Glisser mes doigts dans les cheveux d'Esméralda" },
      { at: 251.5, end: 258.0, singer: "BOTH", text: "Esméralda" },
    ],
  },
  {
    id: "xy",
    title: "XY",
    artist: "Vitaa, Slimane",
    genre: "Pop / Variété",
    duration: 160,
    durationLabel: "2:40",
    bpm: 120,
    key: "F# min",
    cover: "/covers/XY.jpg",
    audioUrl: "/audio/xy.mp3",
    color: "#e11d48",
    accent: "#fda4af",
    lyrics: [
      { at: 0.24, end: 2.47, singer: "A", text: "C'est quoi un homme" },
      { at: 2.47, end: 6.07, singer: "A", text: "Quand il se taire, quand il se cache pour pleurer" },
      { at: 6.07, end: 10.28, singer: "A", text: "Quand il a peur, quand il a mal à en crever" },
      { at: 10.28, end: 14.24, singer: "A", text: "C'est quoi un homme, quand il est lui, qu'il ne ment pas" },
      { at: 14.24, end: 16.54, singer: "A", text: "C'est quoi un homme" },
      { at: 16.54, end: 18.18, singer: "B", text: "C'est fort une femme" },
      { at: 18.18, end: 20.47, singer: "B", text: "Quand on nous blesse et nous accable" },
      { at: 20.47, end: 22.32, singer: "B", text: "On ne se plaint pas" },
      { at: 22.32, end: 24.47, singer: "B", text: "Quand on nous laisse, que tout le monde part" },
      { at: 24.47, end: 26.33, singer: "B", text: "On reste là" },
      { at: 26.33, end: 28.56, singer: "B", text: "Avec les restes on reconstruit" },
      { at: 28.56, end: 30.31, singer: "B", text: "On est comme ça" },
      { at: 30.31, end: 32.68, singer: "B", text: "C'est ça une femme" },
      { at: 32.68, end: 34.13, singer: "BOTH", text: "C'est quoi un homme" },
      { at: 34.13, end: 36.16, singer: "BOTH", text: "C'est quoi une femme" },
      { at: 36.16, end: 40.77, singer: "BOTH", text: "On fait semblant, on joue le jeu qu'on nous apprend" },
      { at: 40.77, end: 42.12, singer: "A", text: "Si t'es un homme" },
      { at: 42.12, end: 45.70, singer: "B", text: "Si t'es une femme" },
      { at: 45.70, end: 48.13, singer: "B", text: "C'est quoi une femme" },
      { at: 48.13, end: 51.93, singer: "B", text: "Quand on l'empêche, quand on aimerait qu'elle ne dise rien" },
      { at: 51.93, end: 56.18, singer: "B", text: "Quand on la laisse, quand on l'enferme dans un coin" },
      { at: 56.18, end: 57.32, singer: "B", text: "C'est quoi une femme" },
      { at: 57.32, end: 60.34, singer: "B", text: "Quand elle a peur de tes mains" },
      { at: 60.34, end: 62.15, singer: "B", text: "C'est quoi une femme" },
      { at: 62.15, end: 64.13, singer: "A", text: "C'est beau un homme" },
      { at: 64.13, end: 67.99, singer: "A", text: "Qui n'a plus peur quand il faut protéger les siens" },
      { at: 67.99, end: 72.29, singer: "A", text: "Devant sa mère, même le plus fort ne dit plus rien" },
      { at: 72.29, end: 76.20, singer: "A", text: "C'est beau un homme qui ne trompe pas, qui se contient" },
      { at: 76.20, end: 78.17, singer: "A", text: "C'est beau un homme" },
      { at: 78.17, end: 80.27, singer: "BOTH", text: "C'est quoi un homme" },
      { at: 80.27, end: 82.24, singer: "BOTH", text: "C'est quoi une femme" },
      { at: 82.24, end: 86.04, singer: "BOTH", text: "On fait semblant, on joue le jeu qu'on nous apprend" },
      { at: 86.04, end: 88.24, singer: "A", text: "Si t'es un homme" },
      { at: 88.24, end: 91.92, singer: "B", text: "Si t'es une femme" },
      { at: 91.92, end: 94.38, singer: "B", text: "On nous demande" },
      { at: 94.38, end: 96.48, singer: "B", text: "D'être l'épaule, d'être les bras" },
      { at: 96.48, end: 98.30, singer: "B", text: "De rester là" },
      { at: 98.30, end: 100.54, singer: "B", text: "Et de sourire devant les gens" },
      { at: 100.54, end: 102.00, singer: "B", text: "Quand rien ne va" },
      { at: 102.00, end: 106.28, singer: "B", text: "On se demande bien trop de choses qu'on ne sait pas" },
      { at: 106.28, end: 107.97, singer: "B", text: "On se demande" },
      { at: 107.97, end: 110.28, singer: "A", text: "Si on pardonne" },
      { at: 110.28, end: 113.97, singer: "A", text: "La différence et toutes les remises en question" },
      { at: 113.97, end: 118.03, singer: "A", text: "Si on oublie les idéaux, les illusions" },
      { at: 118.03, end: 122.10, singer: "A", text: "Si on pardonne les faux pas, les déceptions" },
      { at: 122.10, end: 124.23, singer: "A", text: "Je te pardonne" },
      { at: 124.23, end: 126.31, singer: "BOTH", text: "C'est quoi un homme" },
      { at: 126.31, end: 128.13, singer: "BOTH", text: "C'est quoi une femme" },
      { at: 128.13, end: 132.13, singer: "BOTH", text: "On fait semblant, on joue le jeu qu'on nous apprend" },
      { at: 132.13, end: 134.15, singer: "A", text: "Si t'es un homme" },
      { at: 134.15, end: 138.35, singer: "B", text: "Si t'es une femme" },
      { at: 138.35, end: 140.62, singer: "A", text: "C'est quoi un homme" },
      { at: 140.62, end: 144.27, singer: "A", text: "Quand il se taire, quand il se cache pour pleurer" },
      { at: 144.27, end: 148.28, singer: "A", text: "Quand il a peur, quand il a mal à en crever" },
      { at: 148.28, end: 152.36, singer: "BOTH", text: "Devant sa mère, même le plus fort ne dit plus rien" },
      { at: 152.36, end: 156.00, singer: "BOTH", text: "C'est quoi un homme" },
    ],
  },
  {
    id: "ils-nous-connaissent-pas",
    title: "Ils nous connaissent pas",
    artist: "Soprano",
    genre: "Rap / Pop urbaine",
    duration: 246,
    durationLabel: "4:06",
    bpm: 96,
    key: "F# min",
    cover: "/covers/ils-nous-connaissent-pas.jpg",
    audioUrl: "/audio/ils-nous-connaissent-pas.mp3",
    color: "#0284c7",
    accent: "#7dd3fc",
    lyrics: [
      { at: 12.82, end: 15.52, singer: "A", text: "Ils nous connaissent pas" },
      { at: 15.52, end: 19.68, singer: "A", text: "No no no no no" },
      { at: 19.68, end: 22.39, singer: "B", text: "Ils nous connaissent pas" },
      { at: 22.39, end: 26.40, singer: "B", text: "No no no no no" },
      { at: 26.40, end: 28.03, singer: "BOTH", text: "Aujourd'hui ils nous parlent" },
      { at: 28.03, end: 31.37, singer: "BOTH", text: "D'identité nationale, d'Europe etc" },
      { at: 31.37, end: 35.77, singer: "BOTH", text: "Pendant que la jeunesse ne sait plus où elle va" },
      { at: 35.77, end: 40.89, singer: "BOTH", text: "No no no no no" },
      { at: 40.89, end: 44.12, singer: "A", text: "À l'école tu peux voir des Saïd et Nicolas" },
      { at: 44.12, end: 47.58, singer: "A", text: "Mais pourtant en Histoire certaines se reconnaissent pas" },
      { at: 47.58, end: 50.98, singer: "A", text: "Ils nous parlent de Mozart, Beethoven et tralala" },
      { at: 50.98, end: 54.26, singer: "A", text: "Alors qu'on a dans le casque du hip hop en mp3" },
      { at: 54.26, end: 57.43, singer: "B", text: "La casquette à l'envers, le langage l'est aussi" },
      { at: 57.43, end: 60.83, singer: "B", text: "Le regard de travers, la politesse l'est aussi" },
      { at: 60.83, end: 64.24, singer: "B", text: "Le Levis ras des fesses, la casquette à ras du cou" },
      { at: 64.24, end: 67.57, singer: "B", text: "Ça ne parle qu'en sms, la grammaire on ne connaît plus" },
      { at: 67.57, end: 71.05, singer: "A", text: "Alcoolique à 13 ans, même le shit ne fait plus rien" },
      { at: 71.05, end: 74.29, singer: "A", text: "Aller retour en prison, les parents ne font plus rien" },
      { at: 74.29, end: 77.58, singer: "B", text: "Des parents divorcés comme pour tous mes collègues" },
      { at: 77.58, end: 82.24, singer: "B", text: "Donc ça boit pour oublier, oui, comme pour tous mes collègues" },
      { at: 82.24, end: 86.37, singer: "BOTH", text: "No no no no no" },
      { at: 86.37, end: 88.81, singer: "A", text: "Ils nous connaissent pas" },
      { at: 88.81, end: 93.08, singer: "A", text: "No no no no no" },
      { at: 93.08, end: 94.68, singer: "BOTH", text: "Aujourd'hui ils nous parlent" },
      { at: 94.68, end: 98.01, singer: "BOTH", text: "D'identité nationale, d'Europe etc" },
      { at: 98.01, end: 102.28, singer: "BOTH", text: "Pendant que la jeunesse ne sait plus où elle va" },
      { at: 102.28, end: 107.40, singer: "BOTH", text: "No no no no no" },
      { at: 107.40, end: 110.85, singer: "A", text: "Papa boit tout les soirs, trop de factures à payer" },
      { at: 110.85, end: 114.24, singer: "A", text: "Maman pleure au parloir, petit frère a replongé" },
      { at: 114.24, end: 117.45, singer: "A", text: "Mon grand frère, joint aux lèvres, me dit d'arrêter de fumer" },
      { at: 117.45, end: 120.77, singer: "A", text: "Et ma sœur la diplômée, taf au rayon surgelé" },
      { at: 120.77, end: 124.17, singer: "B", text: "Ma conseillère d'orientation m'oriente en BEP" },
      { at: 124.17, end: 127.55, singer: "B", text: "Elle me verrait bien maçon ou agent de sécurité" },
      { at: 127.55, end: 129.18, singer: "B", text: "Moi j'sais pas ce que je veux faire" },
      { at: 129.18, end: 130.67, singer: "B", text: "Pourquoi faire un taf honnête" },
      { at: 130.67, end: 134.09, singer: "B", text: "Au quartier ils sont millionnaires en vendant des savonnettes" },
      { at: 134.09, end: 137.74, singer: "A", text: "J'veux la dernière paire de Nike, rouler en BMW" },
      { at: 137.74, end: 140.94, singer: "A", text: "Que toutes les filles me remarquent, mais pour tout ça faut des billets" },
      { at: 140.94, end: 144.28, singer: "B", text: "Donc je vole pour m'habiller avec tous mes collègues" },
      { at: 144.28, end: 148.67, singer: "B", text: "Ou je bois pour oublier, oui, comme pour tous mes collègues" },
      { at: 148.67, end: 153.03, singer: "BOTH", text: "No no no no no" },
      { at: 153.03, end: 155.77, singer: "B", text: "Ils nous connaissent pas" },
      { at: 155.77, end: 159.73, singer: "B", text: "No no no no no" },
      { at: 159.73, end: 161.56, singer: "BOTH", text: "Aujourd'hui ils nous parlent" },
      { at: 161.56, end: 164.80, singer: "BOTH", text: "D'identité nationale, d'Europe etc" },
      { at: 164.80, end: 168.98, singer: "BOTH", text: "Pendant que la jeunesse ne sait plus où elle va" },
      { at: 168.98, end: 174.83, singer: "BOTH", text: "No no no no no" },
      { at: 174.83, end: 178.46, singer: "A", text: "Je ne sais pas où je vais, je ne sais pas d'où je viens" },
      { at: 178.46, end: 181.66, singer: "A", text: "Je parle à la lune en tirant sur un joint" },
      { at: 181.66, end: 188.21, singer: "A", text: "Mais dis-moi qui me connaît vraiment" },
      { at: 188.21, end: 191.70, singer: "B", text: "J'ai perdu la notion du bien et du mal" },
      { at: 191.70, end: 195.13, singer: "B", text: "À cause des jugements qu'ils portent sur moi" },
      { at: 195.13, end: 199.42, singer: "B", text: "Pourtant tu trouveras de l'or en moi" },
      { at: 199.42, end: 202.47, singer: "A", text: "Ils nous connaissent pas" },
      { at: 202.47, end: 206.22, singer: "A", text: "No no no no no" },
      { at: 206.22, end: 208.93, singer: "B", text: "Ils nous connaissent pas" },
      { at: 208.93, end: 213.14, singer: "B", text: "No no no no no" },
      { at: 213.14, end: 214.94, singer: "BOTH", text: "Aujourd'hui ils nous parlent" },
      { at: 214.94, end: 218.30, singer: "BOTH", text: "D'identité nationale, d'Europe etc" },
      { at: 218.30, end: 222.30, singer: "BOTH", text: "Pendant que la jeunesse ne sait plus où elle va" },
      { at: 222.30, end: 235.00, singer: "BOTH", text: "No no no no no" },
    ],
  },
];

export function getTrack(trackId: string) {
  return tracks.find((track) => track.id === trackId);
}

